services:
  - type: web
    name: dad-news
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /health
